#+title: Container images for Wire-Cell Toolkit

This repository holds support for building Linux container images
relevant to the Wire-Cell Toolkit.

* Requirements

Each image is described in a Dockerfile and you are free to use them
to build images in your favorite way.

A subset are built automatically which requires ~podman~ and ~singularity~
to be installed.

* Building

The images are factored and thus have interdependence.  To get that
correct, their builds are automated:

#+begin_example
  $ waf configure build
  $ ls build/*.sif
#+end_example

If you wish to install the built Singularity containers to a ~$prefix/containers/singularity/~:

#+begin_example
  $ waf configure --prefix=$HOME/.local
  $ waf build install
#+end_example

By default images are produced with the "owner" of "wirecell" which
matters for the name in the ~podman~ store and the file name for the
Singularity image.  Another owner can be set:

#+begin_example
  $ waf --owner myname
  $ ls build/myname-*.sif
#+end_example

* Using

Below are some basic commands to get started.

** Singularity

By default, Singularity makes your host files visible and writable in
the container.

*** Single commands

#+begin_example
  $ ./build/wirecell-sluser.sif lsb_release -a
  LSB Version:	:core-4.1-amd64:core-4.1-noarch
  Distributor ID:	Scientific
  Description:	Scientific Linux release 7.9 (Nitrogen)
  Release:	7.9
  Codename:	Nitrogen
#+end_example

*** Interactive 

#+begin_example
  $ singularity shell --cleanenv --env TERM=xterm --bind /cvmfs build/wirecell-sluser.sif 
  
  Singularity> source /cvmfs/larsoft.opensciencegrid.org/setup_larsoft.sh 
  Singularity> setup larsoft v09_77_00 -q c14:prof
  Singularity> art --version
  art 3.12.00
  Singularity> exit
#+end_example

** Podman

t.b.d.

* Cleaning up

To remove ~build/~:
#+begin_example
  $ waf distclean
#+end_example

The local podman will fill:

#+begin_example
  $ podman image ls
#+end_example

Any "dangling" images can be pruned:

#+begin_example
  $ podman image prune
#+end_example

Or remove things piecemeal:

#+begin_example
  $ podman image rm localhost/wirecell/slscisoft
  $ podman image rm localhost/wirecell/sluser
#+end_example


* Other info

- Some notes on use of [[file:docs/podman.org][podman]].
- How to exploit [[file:docs/direnv.org][direnv]] to make development with a container easier.
