# podman build -t wirecell/sluser sluser/ 
FROM wirecell/slscisoft
MAINTAINER Brett Viren <brett.viren@gmail.com>

# extra packages
RUN yum -y install \
    bash curl wget tar hostname lbzip2 which git \
    make cmake bison pkgconfig emacs jq vim time bzip2 \
    valgrind graphviz xauth xdg-utils

# direnv
RUN curl -sfL https://direnv.net/install.sh | bin_path=/usr/local/bin bash

# bats
RUN git clone https://github.com/bats-core/bats-core.git && cd bats-core && ./install.sh /usr/local

COPY --chmod=444 wcls.bashrc /etc/profile.d/wcls.sh
COPY --chmod=444 wcls.direnvrc /etc/direnv/lib/wcls.sh

# RUN useradd -ms /usr/bin/bash user -g users
# USER user
# WORKDIR /home/user/

#RUN mkdir -p .ssh

#ENTRYPOINT ["/bin/bash", "-c"]
ENTRYPOINT []
